name: Push
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # - name: Test Docker
            #   run: docker-compose up test
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.15.0'

            - name: Test App
              working-directory: ./app
              run: |
                npm install
                npm run test